name: Python Package CI/CD

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        python-version: ['3.10', '3.11', '3.12']
#        os: [ ubuntu-latest, macos-latest, windows-latest ]
        # TODO: enable the matrix
        python-version: ['3.12']
        os: [ ubuntu-latest ]
        include:
          - os: ubuntu-latest
            path: ~/.cache/pip
          - os: macos-latest
            path: ~/Library/Caches/pip
          - os: windows-latest
            path: ~\AppData\Local\pip\Cache

    steps:

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ${{ matrix.path }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r requirements-dev.txt

    - name: Run linting
      run: make style

    - name: Build and install package
      run: python -m pip install .

    - name: Run tests
      run: make test

  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && needs.build_and_test.result == 'success'
    needs: build_and_test
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install build dependencies
      run: |
        pip install setuptools wheel build

    - name: Build package
      run: python -m build --sdist --wheel

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1



